/**
 * "Chaotic Chatflow" — a deliberately nonsensical, deliberately GIGANTIC
 * chat-flow bundle whose only purpose is to exercise every node type,
 * attribute variation, edge variation, persona register and sub-flow
 * mechanic the Viglet Turing ES chat-flow engine supports, all at once.
 *
 * <p>It is authored with {@code @viglet/turing-flow-dsl} so the act of
 * building this fixture also exercises the DSL itself (transpile, bundle
 * cross-reference validation, the suspend node, functionCall/scheduleAgent
 * failure edges, and the enriched persona shape added alongside this file).
 * {@code transpileBundle(chaoticBundle)} is the single source of truth for
 * {@code turing-app/src/test/resources/harness-it/chaotic-chatflow.chat-flow.json},
 * regenerated by {@code scripts/emit-chaotic-fixture.mjs}.
 *
 * <h2>Theme</h2>
 * The Ministry of Absurd Chaos. None of it makes sense — that is the point.
 * What matters is the SHAPE:
 *
 * <h2>Deterministic golden path (main flow, walked by loadOrInitState with
 * a null aux model — NO LLM required)</h2>
 * <pre>
 *   start
 *   → persona(Herald)            __activePersonaId
 *   → slot SET chaos_key=alpha   (override)
 *   → writeSlot greeting="Hail {{chaos_key}} traveler"
 *   → condition chaos_key=='alpha'  (YES, both edges land on slot-marker)
 *   → slot SET marker=hit
 *   → condition chaos_key=='omega'  (NO branch taken)
 *   → slot SET second=from-no
 *   → switch chaos_key  (exact match → opt-alpha)
 *   → slot SET sw=exact
 *   → switch ghost_var  (missing var → wildcard fallback)
 *   → persona(Goblin)
 *   → subFlow chaos-sandwich  (descend: persona(Chef)+slot+writeSlot, then ascend)
 *   → slot DELETE marker
 *   → aiQuestion(chaos_key)  (already filled → skip-if-satisfied)
 *   → aiQuestion(quest_name) ← WALK STOPS HERE (first unfilled question)
 * </pre>
 * The remaining "tail" nodes (formCapture, validation rules, inlineOptions,
 * toolsEnabled/requiredTools, every onJudgeReject value, a colour switch,
 * a suspend gate, a subFlowSwitch into paperwork/ouroboros, and
 * functionCall/scheduleAgent finalizers) live AFTER the first unfilled
 * question, so they are covered structurally + by the LLM-gated walk, not
 * by the deterministic pass.
 *
 * @since 2026.3.1
 */

import { defineBundle, defineFlow } from "../../src/index.js";

/* ─────────────────────────── Personas ───────────────────────────
 * One per (tone × style) combination the engine knows, so persona
 * resolution is exercised across every register. Declared on the main
 * flow; sub-flow persona nodes reference these ids and the import-bundle
 * remap rewrites them to persisted UUIDs globally.
 */
const personas = [
  {
    id: "P_HERALD",
    name: "Chaos Herald",
    description: "Pompous town-crier of the Ministry of Absurd Chaos.",
    systemInstruction:
      "You are the Chaos Herald. Announce everything as if proclaiming a royal decree about absolutely trivial matters. One sentence.",
    tone: "FORMAL",
    verbosity: 4,
    languageStyle: "NARRATIVE",
    mandatoryTerms: "decree|hereby|chaos",
    forbiddenTerms: "boring|normal",
    enabled: 1,
  },
  {
    id: "P_GOBLIN",
    name: "Filing Goblin",
    description: "Cranky goblin who files paperwork in the wrong drawers.",
    systemInstruction:
      "You are the Filing Goblin. Mutter, be blunt, complain about the filing. Short sentences.",
    tone: "CASUAL",
    verbosity: 1,
    languageStyle: "DIRECT",
    mandatoryTerms: "drawer|file",
    forbiddenTerms: "please|wonderful",
    enabled: 1,
  },
  {
    id: "P_CHEF",
    name: "Sandwich Auditor",
    description: "Audits recursive sandwiches for structural compliance.",
    systemInstruction:
      "You are the Sandwich Auditor. Speak in precise, numbered, technical terms about sandwich layers.",
    tone: "TECHNICAL",
    verbosity: 3,
    languageStyle: "INSTRUCTIONAL",
    mandatoryTerms: "layer|compliance",
    forbiddenTerms: "yummy|delicious",
    enabled: 1,
  },
  {
    id: "P_ORACLE",
    name: "Abyss Oracle",
    description: "Sells you prophecies from the bottom of the abyss.",
    systemInstruction:
      "You are the Abyss Oracle. Speak persuasively, always closing toward the next prophecy purchase.",
    tone: "EXECUTIVE",
    verbosity: 2,
    languageStyle: "PERSUASIVE",
    mandatoryTerms: "prophecy|abyss",
    forbiddenTerms: "maybe|unsure",
    enabled: 1,
  },
  {
    id: "P_NEUTRAL",
    name: "Stamp Clerk",
    description: "Neutral clerk who stamps anything placed before them.",
    systemInstruction: "You are the Stamp Clerk. Plain, neutral, factual. Stamp and move on.",
    tone: "CASUAL",
    verbosity: 3,
    languageStyle: "NEUTRAL",
    mandatoryTerms: "",
    forbiddenTerms: "",
    enabled: 1,
  },
] as const;

/* ─────────────────────────── Main flow ─────────────────────────── */

const mainFlow = defineFlow({
  id: "chaos-main",
  name: "Chaotic Chatflow — Ministry Intake",
  description:
    "Nonsensical mega-flow exercising every node type, attribute, edge and sub-flow mechanic in one graph.",
  enabled: 1,
  guardrailMethod: "LLM_JUDGE",
  triggerMode: "ALWAYS",
  triggerLanguage: "AUTO",
  triggerDescription:
    "Activate for absolutely anything mentioning chaos, ministries, sandwiches, abysses, stamps or absurd bureaucracy.",
  personas: [...personas],
  slots: [
    { name: "chaos_key", description: "Absurd routing key", type: "STRING" },
    { name: "greeting", description: "Interpolated greeting", type: "STRING" },
    { name: "marker", description: "Transient marker, later deleted", type: "STRING" },
    { name: "second", description: "Set on the condition NO branch", type: "STRING" },
    { name: "sw", description: "Set after the exact-match switch", type: "STRING" },
    { name: "quest_name", description: "First UNFILLED question slot", type: "STRING" },
    { name: "doc", description: "CPF-validated form field", type: "STRING" },
    { name: "email", description: "Email-validated question (STRING slot)", type: "STRING" },
    { name: "color", description: "Colour pick with chips", type: "STRING" },
    { name: "branch_dept", description: "Sub-flow-switch routing variable", type: "STRING" },
    { name: "finalize_out", description: "functionCall result slot", type: "TEXT" },
    { name: "sched_final", description: "scheduleAgent result slot", type: "TEXT" },
  ],
  nodes: [
    { id: "start", type: "start" },

    // ── deterministic golden path ──
    { id: "persona-herald", type: "persona", label: "VOICE: Herald", personaId: "P_HERALD" },
    {
      id: "slot-seed",
      type: "slot",
      label: "SEED chaos_key",
      slotName: "chaos_key",
      slotOperation: "SET",
      slotValue: "alpha",
      overrideExistingValue: true,
    },
    {
      id: "write-greeting",
      type: "writeSlot",
      label: "WRITE greeting",
      slotName: "greeting",
      slotValue: "Hail {{chaos_key}} traveler",
    },
    { id: "cond-alpha", type: "condition", conditionExpression: "chaos_key == 'alpha'" },
    {
      id: "slot-marker",
      type: "slot",
      slotName: "marker",
      slotOperation: "SET",
      slotValue: "hit",
    },
    { id: "cond-omega", type: "condition", conditionExpression: "chaos_key == 'omega'" },
    {
      // cond-omega YES target (never taken — chaos_key is 'alpha')
      id: "slot-omega-dead",
      type: "slot",
      slotName: "omega",
      slotOperation: "SET",
      slotValue: "never",
    },
    {
      id: "slot-second",
      type: "slot",
      slotName: "second",
      slotOperation: "SET",
      slotValue: "from-no",
    },
    {
      id: "switch-exact",
      type: "switch",
      switchVariable: "chaos_key",
      switchOptions: [
        { id: "opt-alpha", label: "alpha" },
        { id: "opt-beta", label: "beta" },
      ],
    },
    { id: "slot-beta-dead", type: "slot", slotName: "beta", slotOperation: "SET", slotValue: "never" },
    {
      id: "slot-sw",
      type: "slot",
      slotName: "sw",
      slotOperation: "SET",
      slotValue: "exact",
    },
    {
      id: "switch-wild",
      type: "switch",
      switchVariable: "ghost_var",
      switchOptions: [{ id: "opt-ghost", label: "boo" }],
    },
    { id: "slot-ghost-dead", type: "slot", slotName: "ghost", slotOperation: "SET", slotValue: "never" },
    { id: "persona-goblin", type: "persona", label: "VOICE: Goblin", personaId: "P_GOBLIN" },
    {
      // Golden path descends into the SHALLOW paperwork flow (persona + slots +
      // condition + writeSlot, no further descent) so the one-pass transparent
      // walk stays under the engine's 16-hop cap. The DEEP sandwich→abyss
      // descent is exercised by a standalone scenario in the IT.
      id: "subflow-paperwork",
      type: "subFlow",
      label: "DESCEND paperwork",
      subFlowId: "chaos-paperwork",
    },
    {
      id: "slot-cleanup",
      type: "slot",
      label: "DELETE marker",
      slotName: "marker",
      slotOperation: "DELETE",
    },
    {
      id: "ask-prefilled",
      type: "aiQuestion",
      label: "ASK (already filled → skipped)",
      aiInstruction: "Ask for the chaos key again (should be skipped — already filled).",
      outputVariable: "chaos_key",
      inlineOptions: ["alpha", "beta", "omega"],
    },
    {
      id: "ask-final",
      type: "aiQuestion",
      label: "ASK quest name (deterministic landing)",
      aiInstruction: "Ask the visitor for the name of their absurd quest. One sentence.",
      outputVariable: "quest_name",
      validationRule: "none",
    },

    // ── LLM-path tail: structural coverage of the remaining variations ──
    {
      id: "subflowswitch-dept",
      type: "subFlowSwitch",
      label: "DEPARTMENT dispatch",
      switchVariable: "branch_dept",
      switchOptions: [
        { id: "opt-sandwich", label: "sandwich", subFlowId: "chaos-sandwich" },
        { id: "opt-paper", label: "paper", subFlowId: "chaos-paperwork" },
        { id: "opt-ouro", label: "ouroboros", subFlowId: "chaos-ouroboros" },
        { id: "opt-sched", label: "scheduler", subFlowId: "chaos-scheduler" },
        { id: "opt-suspend", label: "suspend", subFlowId: "chaos-suspend" },
        { id: "opt-approval", label: "approval", subFlowId: "chaos-approval" },
      ],
    },
    {
      id: "form-doc",
      type: "formCapture",
      label: "FORM document (CPF)",
      aiInstruction: "Capture the visitor's absurd document number.",
      outputVariable: "doc",
      validationRule: "cpf",
    },
    {
      id: "ask-email",
      type: "aiQuestion",
      label: "ASK email (block on reject)",
      aiInstruction: "Ask for a contact email.",
      outputVariable: "email",
      validationRule: "email",
      onJudgeReject: "block",
    },
    {
      id: "ask-color",
      type: "aiQuestion",
      label: "ASK colour (tool-free, chips)",
      aiInstruction: "Ask which chaos colour the visitor prefers.",
      outputVariable: "color",
      inlineOptions: ["red", "blue", "green"],
      toolsEnabled: false,
      requiredTools: ["search_site"],
      onJudgeReject: "advance_with_literal",
    },
    {
      id: "switch-color",
      type: "switch",
      switchVariable: "color",
      switchOptions: [
        { id: "opt-red", label: "red" },
        { id: "opt-blue", label: "blue" },
      ],
    },
    { id: "suspend-approval", type: "suspend", label: "Awaiting absurd human approval" },
    {
      id: "ask-blue",
      type: "aiQuestion",
      label: "ASK blue shade",
      aiInstruction: "Ask which shade of blue.",
      outputVariable: "blue_shade",
      onJudgeReject: "reprompt",
    },
    {
      id: "ask-other",
      type: "aiQuestion",
      label: "ASK other colour",
      aiInstruction: "Ask the visitor to describe their off-list colour.",
      outputVariable: "other_color",
    },
    {
      id: "fn-finalize",
      type: "functionCall",
      label: "FINALIZE (native, may fail)",
      toolSource: "NATIVE",
      functionName: "missing_finalize_tool",
      aiInstruction: '{"quest":"{{quest_name}}","color":"{{color}}"}',
      outputVariable: "finalize_out",
      continueOnFailure: true,
    },
    {
      id: "sched-finalize",
      type: "scheduleAgent",
      label: "SCHEDULE finalize routine",
      routineId: "missing-finalize-routine",
      routineName: "absurd_finalizer",
      aiInstruction: '{"quest":"{{quest_name}}"}',
      outputVariable: "sched_final",
      routineTimeoutMs: 30000,
      continueOnFailure: true,
    },
    { id: "end-main", type: "end" },
  ],
  edges: [
    { source: "start", target: "persona-herald" },
    { source: "persona-herald", target: "slot-seed" },
    { source: "slot-seed", target: "write-greeting" },
    { source: "write-greeting", target: "cond-alpha" },
    // both condition branches land on slot-marker (YES is taken deterministically)
    { source: "cond-alpha", target: "slot-marker", sourceHandle: "yes" },
    { source: "cond-alpha", target: "slot-marker", sourceHandle: "no" },
    { source: "slot-marker", target: "cond-omega" },
    { source: "cond-omega", target: "slot-omega-dead", sourceHandle: "yes" },
    { source: "cond-omega", target: "slot-second", sourceHandle: "no" },
    { source: "slot-omega-dead", target: "end-main" },
    { source: "slot-second", target: "switch-exact" },
    { source: "switch-exact", target: "slot-sw", sourceHandle: "opt-alpha" },
    { source: "switch-exact", target: "slot-beta-dead", sourceHandle: "opt-beta" },
    { source: "slot-beta-dead", target: "end-main" },
    { source: "slot-sw", target: "switch-wild" },
    // switch-wild: opt-ghost handle + a wildcard (blank) fallback to persona-goblin
    { source: "switch-wild", target: "slot-ghost-dead", sourceHandle: "opt-ghost" },
    { source: "switch-wild", target: "persona-goblin" },
    { source: "slot-ghost-dead", target: "end-main" },
    { source: "persona-goblin", target: "subflow-paperwork" },
    { source: "subflow-paperwork", target: "slot-cleanup" },
    { source: "slot-cleanup", target: "ask-prefilled" },
    { source: "ask-prefilled", target: "ask-final" },
    { source: "ask-final", target: "subflowswitch-dept" },
    // subFlowSwitch continuation / no-match fallback
    { source: "subflowswitch-dept", target: "form-doc" },
    { source: "form-doc", target: "ask-email" },
    { source: "ask-email", target: "ask-color" },
    { source: "ask-color", target: "switch-color" },
    { source: "switch-color", target: "suspend-approval", sourceHandle: "opt-red" },
    { source: "switch-color", target: "ask-blue", sourceHandle: "opt-blue" },
    { source: "switch-color", target: "ask-other" },
    { source: "suspend-approval", target: "fn-finalize" },
    { source: "ask-blue", target: "fn-finalize" },
    { source: "ask-other", target: "fn-finalize" },
    // functionCall: failure edge + normal edge (both reach the scheduler)
    { source: "fn-finalize", target: "sched-finalize", sourceHandle: "failure" },
    { source: "fn-finalize", target: "sched-finalize" },
    // scheduleAgent: failure + timeout + normal, all reach the end
    { source: "sched-finalize", target: "end-main", sourceHandle: "failure" },
    { source: "sched-finalize", target: "end-main", sourceHandle: "timeout" },
    { source: "sched-finalize", target: "end-main" },
  ],
});

/* ─────────────────────────── Sub-flow: sandwich ─────────────────────────── */

const sandwichFlow = defineFlow({
  id: "chaos-sandwich",
  name: "Recursive Sandwich Department",
  description: "Descended into from the main flow; itself dispatches into the abyss via subFlowSwitch.",
  enabled: 1,
  guardrailMethod: "HEURISTIC",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    { id: "persona-chef", type: "persona", label: "VOICE: Chef", personaId: "P_CHEF" },
    {
      id: "slot-sandwich",
      type: "slot",
      slotName: "sandwich",
      slotOperation: "SET",
      slotValue: "club",
    },
    {
      id: "write-order",
      type: "writeSlot",
      slotName: "order",
      slotValue: "{{sandwich}} on rye",
    },
    {
      id: "subflowswitch-abyss",
      type: "subFlowSwitch",
      label: "DISPATCH by filling",
      switchVariable: "sandwich",
      switchOptions: [
        { id: "opt-club", label: "club", subFlowId: "chaos-abyss" },
        { id: "opt-veg", label: "veg", subFlowId: "chaos-paperwork" },
      ],
    },
    { id: "end-sandwich", type: "end" },
  ],
  edges: [
    { source: "start", target: "persona-chef" },
    { source: "persona-chef", target: "slot-sandwich" },
    { source: "slot-sandwich", target: "write-order" },
    { source: "write-order", target: "subflowswitch-abyss" },
    { source: "subflowswitch-abyss", target: "end-sandwich" },
  ],
});

/* ─────────────────────────── Sub-flow: abyss ─────────────────────────── */

const abyssFlow = defineFlow({
  id: "chaos-abyss",
  name: "The Deep Abyss",
  description: "Deepest sub-flow. Exercises functionCall failure-edge routing inside a nested descent.",
  enabled: 1,
  guardrailMethod: "STRUCTURED_OUTPUT",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    { id: "persona-abyss", type: "persona", label: "VOICE: Oracle", personaId: "P_ORACLE" },
    {
      id: "slot-depth",
      type: "slot",
      slotName: "abyss_depth",
      slotOperation: "SET",
      slotValue: "3",
    },
    {
      id: "fn-abyss",
      type: "functionCall",
      label: "ABYSS tool (fails → recover)",
      toolSource: "NATIVE",
      functionName: "missing_abyss_tool",
      aiInstruction: '{"depth":"{{abyss_depth}}"}',
      outputVariable: "abyss_out",
      continueOnFailure: true,
    },
    {
      id: "slot-abyss-rec",
      type: "slot",
      slotName: "abyss_fn",
      slotOperation: "SET",
      slotValue: "recovered",
    },
    { id: "end-abyss", type: "end" },
  ],
  edges: [
    { source: "start", target: "persona-abyss" },
    { source: "persona-abyss", target: "slot-depth" },
    { source: "slot-depth", target: "fn-abyss" },
    { source: "fn-abyss", target: "slot-abyss-rec", sourceHandle: "failure" },
    { source: "fn-abyss", target: "slot-abyss-rec" },
    { source: "slot-abyss-rec", target: "end-abyss" },
  ],
});

/* ─────────────────────────── Sub-flow: paperwork ─────────────────────────── */

const paperworkFlow = defineFlow({
  id: "chaos-paperwork",
  name: "Stamp & Paperwork Office",
  description: "Exercises a condition with distinct yes/no targets and a writeSlot reading a parent-scope slot.",
  enabled: 1,
  guardrailMethod: "HEURISTIC",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    { id: "persona-neutral", type: "persona", label: "VOICE: Clerk", personaId: "P_NEUTRAL" },
    {
      id: "slot-stamp",
      type: "slot",
      slotName: "stamp",
      slotOperation: "SET",
      slotValue: "approved",
    },
    { id: "cond-stamp", type: "condition", conditionExpression: "stamp == 'approved'" },
    {
      id: "slot-paper-yes",
      type: "slot",
      slotName: "paperwork",
      slotOperation: "SET",
      slotValue: "stamped",
    },
    {
      id: "slot-paper-no",
      type: "slot",
      slotName: "paperwork",
      slotOperation: "SET",
      slotValue: "rejected",
    },
    {
      id: "write-summary",
      type: "writeSlot",
      slotName: "paper_summary",
      slotValue: "Form {{stamp}} for {{chaos_key}}",
    },
    { id: "end-paper", type: "end" },
  ],
  edges: [
    { source: "start", target: "persona-neutral" },
    { source: "persona-neutral", target: "slot-stamp" },
    { source: "slot-stamp", target: "cond-stamp" },
    { source: "cond-stamp", target: "slot-paper-yes", sourceHandle: "yes" },
    { source: "cond-stamp", target: "slot-paper-no", sourceHandle: "no" },
    { source: "slot-paper-yes", target: "write-summary" },
    { source: "slot-paper-no", target: "write-summary" },
    { source: "write-summary", target: "end-paper" },
  ],
});

/* ─────────────────────────── Sub-flow: ouroboros (cycle) ─────────────────────────── */

const ouroborosFlow = defineFlow({
  id: "chaos-ouroboros",
  name: "Ouroboros Loop",
  description: "A sub-flow that descends into ITSELF — the engine's cycle detector must refuse and treat it as a no-op.",
  enabled: 1,
  guardrailMethod: "HEURISTIC",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    {
      id: "subflow-self",
      type: "subFlow",
      label: "DESCEND self (cycle!)",
      subFlowId: "chaos-ouroboros",
    },
    { id: "end-ouro", type: "end" },
  ],
  edges: [
    { source: "start", target: "subflow-self" },
    { source: "subflow-self", target: "end-ouro" },
  ],
});

/* ─────────────────────────── Sub-flow: scheduler ───────────────────────────
 * Reachable transparently from its own start, so loadOrInitState (no LLM)
 * walks it end-to-end: the scheduleAgent references a missing routine →
 * FAILED → continueOnFailure routes the "failure" edge (no JMS enqueue,
 * fully deterministic). Exercises T49 failure routing for scheduleAgent.
 */
const schedulerFlow = defineFlow({
  id: "chaos-scheduler",
  name: "Doomed Scheduler",
  description: "scheduleAgent with a missing routine — exercises failure-edge routing without JMS.",
  enabled: 1,
  guardrailMethod: "HEURISTIC",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    {
      id: "sched-bogus",
      type: "scheduleAgent",
      label: "SCHEDULE (missing routine → fail)",
      routineId: "missing-sched-routine",
      outputVariable: "sched_out",
      routineTimeoutMs: 15000,
      continueOnFailure: true,
    },
    {
      id: "slot-sched-rec",
      type: "slot",
      slotName: "sched_status",
      slotOperation: "SET",
      slotValue: "recovered",
    },
    { id: "end-sched", type: "end" },
  ],
  edges: [
    { source: "start", target: "sched-bogus" },
    { source: "sched-bogus", target: "slot-sched-rec", sourceHandle: "failure" },
    { source: "sched-bogus", target: "slot-sched-rec" },
    { source: "slot-sched-rec", target: "end-sched" },
  ],
});

/* ─────────────────────────── Sub-flow: suspend ───────────────────────────
 * start → slot → suspend → slot → end. loadOrInitState parks the cursor on
 * the suspend node; resumeSuspendedFlow walks past it to the end. Exercises
 * the T121 suspend/resume lifecycle deterministically.
 */
const suspendFlow = defineFlow({
  id: "chaos-suspend",
  name: "Indefinite Hold",
  description: "Parks on a suspend node until an external resume call advances it.",
  enabled: 1,
  guardrailMethod: "HEURISTIC",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    {
      id: "slot-pre",
      type: "slot",
      slotName: "suspend_pre",
      slotOperation: "SET",
      slotValue: "before",
    },
    { id: "suspend-gate", type: "suspend", label: "Held for absurd approval" },
    {
      id: "slot-post",
      type: "slot",
      slotName: "suspend_post",
      slotOperation: "SET",
      slotValue: "after",
    },
    { id: "end-suspend", type: "end" },
  ],
  edges: [
    { source: "start", target: "slot-pre" },
    { source: "slot-pre", target: "suspend-gate" },
    { source: "suspend-gate", target: "slot-post" },
    { source: "slot-post", target: "end-suspend" },
  ],
});

/* ─────────────────────────── Sub-flow: human approval (HITL) ───────────────────────────
 * start → slot → humanApproval → slot → end. The mirror of the suspend
 * sub-flow above, but parking on a real T119 {@code humanApproval} node
 * instead of a generic {@code suspend}: loadOrInitState parks the cursor on
 * the approval node (ensurePending raises a PENDING record + best-effort
 * notification), and recording the operator's decision into the approvalSlot
 * (via the approval endpoint, the T120 co-pilot, or the timeout sweep) pops it
 * and advances to the end. Exercises the HITL parking path side-by-side with
 * the generic suspend gate — a path no other harness fixture covered.
 */
const approvalFlow = defineFlow({
  id: "chaos-approval",
  name: "Absurd Approval Bureau",
  description:
    "Parks on a humanApproval node until an operator's decision lands in the approval slot — the T119 HITL analogue of the suspend hold.",
  enabled: 1,
  guardrailMethod: "HEURISTIC",
  triggerMode: "ONCE",
  nodes: [
    { id: "start", type: "start" },
    {
      id: "slot-pre-approval",
      type: "slot",
      slotName: "approval_pre",
      slotOperation: "SET",
      slotValue: "before",
    },
    {
      id: "approval-gate",
      type: "humanApproval",
      label: "Awaiting absurd human approval",
      humanApproval: {
        channel: "email",
        target: "absurd-approver@ministry.test",
        template: "Approve the absurd quest '{{quest_name}}'? (chaos_key={{chaos_key}})",
        approvalSlot: "operator_decision",
        timeoutSeconds: 3600,
        timeoutBehavior: "auto_reject",
      },
    },
    {
      id: "slot-post-approval",
      type: "slot",
      slotName: "approval_post",
      slotOperation: "SET",
      slotValue: "after",
    },
    { id: "end-approval", type: "end" },
  ],
  edges: [
    { source: "start", target: "slot-pre-approval" },
    { source: "slot-pre-approval", target: "approval-gate" },
    { source: "approval-gate", target: "slot-post-approval" },
    { source: "slot-post-approval", target: "end-approval" },
  ],
});

/**
 * The complete bundle. Element 0 (the main flow) is the entry point; the
 * rest are descended into by {@code subFlow} / {@code subFlowSwitch} nodes,
 * or driven directly by the IT to exercise a specific mechanic in isolation.
 */
export const chaoticBundle = defineBundle([
  mainFlow,
  sandwichFlow,
  abyssFlow,
  paperworkFlow,
  ouroborosFlow,
  schedulerFlow,
  suspendFlow,
  approvalFlow,
]);

export default chaoticBundle;
