const consolePath: string = import.meta.env.VITE_CONSOLE_CONTEXT_PATH;
export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  LOGOUT: "/logout",
  SETUP: "/setup",
  CONSOLE: consolePath,
  HOME: `${consolePath}/home`,
  SN_SEARCH: `/sn`,
  ANN_SEARCH: `/ann`,
  SN_ROOT: `${consolePath}/sn`,
  SN_INSTANCE: `${consolePath}/sn/instance`,
  SN_ONBOARDING: `${consolePath}/sn/onboarding`,
  SE_ROOT: `${consolePath}/se`,
  SE_INSTANCE: `${consolePath}/se/instance`,
  STORE_ROOT: `${consolePath}/store`,
  STORE_INSTANCE: `${consolePath}/store/instance`,
  TOKEN_ROOT: `${consolePath}/token`,
  TOKEN_INSTANCE: `${consolePath}/token/instance`,
  LLM_ROOT: `${consolePath}/llm`,
  LLM_INSTANCE: `${consolePath}/llm/instance`,
  INTEGRATION_ROOT: `${consolePath}/integration`,
  INTEGRATION_INSTANCE: `${consolePath}/integration/instance`,
  LOGGING_INSTANCE: `${consolePath}/admin-settings/logging`,
  DASHBOARD: `${consolePath}/dashboard`,
  GLOBAL_SETTINGS: `${consolePath}/global-settings`,
  EXCHANGE_IMPORT: `${consolePath}/admin-settings/import`,
  CHAT_ROOT: `${consolePath}/chat`,
  GRAPHQL_ROOT: `${consolePath}/graphql`,
  USER_ACCOUNT: `${consolePath}/user/account`,
  AI_ANALYTICS_ROOT: `${consolePath}/ai-analytics`,
  COST_GOVERNANCE: `${consolePath}/ai-analytics/cost-governance`,
  CHAT_ANALYTICS: `${consolePath}/ai-analytics/chat-analytics`,
  PARKED_CONVERSATIONS: `${consolePath}/ai-analytics/parked-conversations`,
  CAPABILITY_MATRIX: `${consolePath}/ai-analytics/capability-matrix`,
  CONVERSATION_DETAIL: `${consolePath}/conversation`,
  MCP_ROOT: `${consolePath}/mcp`,
  MCP_INSTANCE: `${consolePath}/mcp/instance`,
  CUSTOM_TOOL_ROOT: `${consolePath}/custom-tool`,
  CUSTOM_TOOL_INSTANCE: `${consolePath}/custom-tool/instance`,
  ROUTINE_ROOT: `${consolePath}/routine`,
  ROUTINE_INSTANCE: `${consolePath}/routine/instance`,
  CHAT_WEBHOOK_ROOT: `${consolePath}/chat-webhook`,
  CHAT_WEBHOOK_INSTANCE: `${consolePath}/chat-webhook/instance`,
  AI_AGENT_ROOT: `${consolePath}/ai-agent`,
  AI_AGENT_INSTANCE: `${consolePath}/ai-agent/instance`,
  VOICE_KIOSK: `${consolePath}/voice-kiosk`,
  PERSONA_ROOT: `${consolePath}/persona`,
  PERSONA_INSTANCE: `${consolePath}/persona/instance`,
  ASSET_ROOT: `${consolePath}/asset`,
  SKILL_ROOT: `${consolePath}/skill`,
  TENANT_SETTINGS: `${consolePath}/tenant`,
  TENANT_ADMIN: `${consolePath}/tenant-admin`,
  PAGE_ROOT: `${consolePath}/page`,
  EMBEDDING_MODEL_ROOT: `${consolePath}/embedding-model`,
  EMBEDDING_MODEL_INSTANCE: `${consolePath}/embedding-model/instance`,
  ADMIN_ROOT: `${consolePath}/admin-settings`,
  ADMIN_USERS: `${consolePath}/admin-settings/users`,
  ADMIN_GROUPS: `${consolePath}/admin-settings/groups`,
  ADMIN_ROLES: `${consolePath}/admin-settings/roles`,
  ADMIN_SETTINGS: `${consolePath}/admin-settings/settings`,
  ADMIN_TOKENS: `${consolePath}/admin-settings/tokens`,
  ADMIN_SYSTEM_INFO: `${consolePath}/admin-settings/system-info`,
  GIT_ROOT: `${consolePath}/git`,
  GIT_INSTANCE: `${consolePath}/git/instance`,
  MARKETPLACE_ROOT: `${consolePath}/marketplace`,
  REGISTER: "/register",
  BENTO_ROOT: "/bento",
  BENTO_HOME: "/bento/home",
  // Section "hub" pages (T573) — the nav rail lists these, not the ~22 leaves.
  BENTO_AREA_GENERATIVE_AI: "/bento/area/generative-ai",
  BENTO_AREA_ENTERPRISE_SEARCH: "/bento/area/enterprise-search",
  BENTO_AREA_MANAGEMENT: "/bento/area/management",
  BENTO_AI_AGENT: "/bento/ai-agent",
  BENTO_AI_AGENT_INSTANCE: "/bento/ai-agent/instance",
  BENTO_LLM: "/bento/llm",
  BENTO_LLM_INSTANCE: "/bento/llm/instance",
  BENTO_LLM_ADVISOR: "/bento/llm/advisor",
  // Block AG Phase 1 — BYO-infra & simple CRUD surfaces.
  BENTO_SE: "/bento/se",
  BENTO_SE_INSTANCE: "/bento/se/instance",
  BENTO_STORE: "/bento/store",
  BENTO_STORE_INSTANCE: "/bento/store/instance",
  BENTO_EMBEDDING_MODEL: "/bento/embedding",
  BENTO_EMBEDDING_MODEL_INSTANCE: "/bento/embedding/instance",
  BENTO_TOKEN: "/bento/token",
  BENTO_TOKEN_INSTANCE: "/bento/token/instance",
  // Block AZ (§XLIX) — Governed LLM Gateway admin.
  BENTO_GATEWAY: "/bento/gateway",
  BENTO_INTEGRATION: "/bento/integration",
  BENTO_INTEGRATION_INSTANCE: "/bento/integration/instance",
  BENTO_MCP: "/bento/mcp",
  BENTO_MCP_INSTANCE: "/bento/mcp/instance",
  BENTO_CUSTOM_TOOL: "/bento/custom-tool",
  BENTO_CUSTOM_TOOL_INSTANCE: "/bento/custom-tool/instance",
  BENTO_ROUTINE: "/bento/routine",
  BENTO_ROUTINE_INSTANCE: "/bento/routine/instance",
  BENTO_CHAT_WEBHOOK: "/bento/chat-webhook",
  BENTO_CHAT_WEBHOOK_INSTANCE: "/bento/chat-webhook/instance",
  BENTO_PERSONA: "/bento/persona",
  BENTO_PERSONA_INSTANCE: "/bento/persona/instance",
  BENTO_PERSONA_VALIDATE: "/bento/persona/validate",
  BENTO_PERSONA_MATCH: "/bento/persona/match",
  BENTO_PERSONA_DIALOGUE: "/bento/persona/dialogue",
  BENTO_PERSONA_RESEARCH: "/bento/persona/research",
  BENTO_PERSONA_COHORT: "/bento/persona/cohort",
  BENTO_PERSONA_SUGGEST: "/bento/persona/suggest",
  BENTO_GIT: "/bento/git",
  BENTO_GIT_INSTANCE: "/bento/git/instance",

  // Block AG Phase 2 — complex CRUD & editors.
  BENTO_SN: "/bento/sn",
  BENTO_SN_INSTANCE: "/bento/sn/instance",
  BENTO_SN_ONBOARDING: "/bento/sn/onboarding",
  BENTO_SKILL: "/bento/skill",
  /** Block AQ (§XL) — Thesaurus (controlled vocabulary) library. */
  BENTO_THESAURUS: "/bento/thesaurus",
  BENTO_ASSET: "/bento/asset",
  BENTO_PAGE: "/bento/page",

  // Block AG Phase 3 — functional & dashboard surfaces.
  BENTO_CHAT: "/bento/chat",
  /** Block AI / T580 — deterministic agent-scoped chat (append `/:agentId`). */
  BENTO_CHAT_AGENT: "/bento/chat/agent",
  /** Block AI / T580 — deterministic persona-scoped chat (append `/:personaId`). */
  BENTO_CHAT_PERSONA: "/bento/chat/persona",
  BENTO_CONVERSATION: "/bento/conversation",
  BENTO_AI_ANALYTICS: "/bento/ai-analytics",
  BENTO_COST_GOVERNANCE: "/bento/ai-analytics/cost-governance",
  BENTO_GRAPHQL: "/bento/graphql",
  BENTO_DASHBOARD: "/bento/dashboard",
  BENTO_MARKETPLACE: "/bento/marketplace",
  BENTO_GLOBAL_SETTINGS: "/bento/global-settings",
  BENTO_IMPORT: "/bento/import",
  BENTO_LOGGING: "/bento/logging",
  BENTO_SYSTEM_INFO: "/bento/system-info",

  // Block AG Phase 4 — admin & tenancy surfaces.
  BENTO_ADMIN: "/bento/admin",
  BENTO_ADMIN_USERS: "/bento/admin/users",
  BENTO_ADMIN_GROUPS: "/bento/admin/groups",
  BENTO_ADMIN_ROLES: "/bento/admin/roles",
  BENTO_TENANT_SETTINGS: "/bento/tenant",
  BENTO_TENANT_ADMIN: "/bento/tenant-admin",
  BENTO_USER_ACCOUNT: "/bento/user/account",

  // Block AJ — Eval Studio (T599).
  BENTO_EVAL: "/bento/eval",
};
