package com.viglet.turing.api.llm.chat;

import java.io.File;
import java.time.ZoneId;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Locale;
import java.util.Map;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.ContentDisposition;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.viglet.turing.commons.utils.TurCommonsUtils;
import com.viglet.turing.genai.tool.TurCodeInterpreterUrlSigner;
import com.viglet.turing.genai.tool.TurCodeInterpreterUrlSigner.VerifyResult;

import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@RestController
@RequestMapping("/api/v2/code-interpreter")
@Tag(name = "Code Interpreter Files", description = "Serve files generated by the Code Interpreter")
public class TurCodeInterpreterFileAPI {

    private static final String SANDBOX_DIR = "code-interpreter";
    private static final String SESSIONS_DIR = "sessions";
    private static final String TENANTS_DIR = "tenants";

    private final TurCodeInterpreterUrlSigner urlSigner;

    public TurCodeInterpreterFileAPI(TurCodeInterpreterUrlSigner urlSigner) {
        this.urlSigner = urlSigner;
    }

    @GetMapping("/{sessionId}/{filename}")
    public ResponseEntity<Resource> getFile(
            @PathVariable String sessionId,
            @PathVariable String filename,
            @RequestParam(value = "exp", required = false) String exp,
            @RequestParam(value = "sig", required = false) String sig,
            @CookieValue(value = TurCodeInterpreterUrlSigner.CONV_COOKIE, required = false) String convCookie) {
        // Sanitize inputs to prevent path traversal
        if (sessionId.contains("..") || sessionId.contains("/") || sessionId.contains("\\")
                || filename.contains("..") || filename.contains("/") || filename.contains("\\")) {
            return ResponseEntity.badRequest().build();
        }

        // HMAC + expiry + cookie-binding gate. Performed BEFORE filesystem
        // resolution so a 403 doesn't leak whether the file exists. When
        // signing is disabled (operator opt-out via config), verify()
        // returns OK and we serve as before.
        VerifyResult verdict = urlSigner.verify(sessionId, filename, exp, sig, convCookie);
        if (verdict != VerifyResult.OK) {
            // Single 403 for any non-OK outcome — the granular enum case
            // is logged for diagnostics but not surfaced to the client so
            // an attacker can't probe which check fails first.
            log.warn("[CodeInterpreterFileAPI] rejecting {}/{}: {}", sessionId, filename, verdict);
            return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
        }

        File sandboxRoot = TurCommonsUtils.addSubDirToStoreDir(SANDBOX_DIR);
        // Session dirs live at `sandboxRoot/sessions/YYYY-MM-DD/{sessionId}/`
        // (date-bucketed by TurCodeInterpreterToolService for cleanup
        // efficiency). The URL exposes only {sessionId} — the file API
        // searches today's bucket first (hottest path), then walks
        // backwards through the day buckets until found. Sessions older
        // than the cleanup TTL are gone anyway.
        File file = resolveSessionFile(sandboxRoot, sessionId, filename);
        if (file == null) {
            return ResponseEntity.notFound().build();
        }

        // Verify the file is actually inside the sandbox
        if (!file.toPath().normalize().startsWith(sandboxRoot.toPath().normalize())) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
        }

        try {
            String mimeType = Files.probeContentType(file.toPath());
            if (mimeType == null) {
                mimeType = mimeTypeFromExtension(filename);
            }
            Resource resource = new FileSystemResource(file);
            // Images (matplotlib charts etc.) must render INLINE so the chat's
            // `![](…)` markdown displays them; forcing `attachment` made the
            // browser download the file and show a broken-image icon instead.
            // Everything else (pdf/csv/xlsx/zip) keeps `attachment` so the
            // "Download …" links still save the file.
            boolean inline = mimeType.startsWith("image/");
            ContentDisposition disposition = (inline
                    ? ContentDisposition.inline()
                    : ContentDisposition.attachment())
                    .filename(filename)
                    .build();
            return ResponseEntity.ok()
                    .contentType(MediaType.parseMediaType(mimeType))
                    .header(HttpHeaders.CONTENT_DISPOSITION, disposition.toString())
                    .body(resource);
        } catch (IOException e) {
            log.error("Failed to serve code interpreter file {}/{}: {}", sessionId, filename, e.getMessage());
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }

    /**
     * Resolves {@code {sessionId}/{filename}} across three possible disk
     * layouts in priority order:
     * <ol>
     *   <li><b>Tenant-isolated</b> ({@code tenants/{agentId}/{conversationId}/YYYY-MM-DD/{sessionId}/})
     *       — current production layout for Custom-Tool invocations.</li>
     *   <li><b>Date-bucketed flat</b> ({@code sessions/YYYY-MM-DD/{sessionId}/})
     *       — legacy fallback for {@code @Tool}-direct calls and pre-2026.2.7 URLs.</li>
     *   <li><b>Pre-date-bucket</b> ({@code {sessionId}/}) — oldest fallback
     *       for URLs minted before the date layout migration.</li>
     * </ol>
     * <p>Each layer tries today's bucket first (overwhelmingly the hot
     * path — visitors usually download right after generation), then
     * sibling date buckets newest-first. Any bucket older than the
     * cleanup TTL won't have the file anymore; the scan only stats
     * dirs that still exist on disk.
     */
    private static File resolveSessionFile(File sandboxRoot, String sessionId, String filename) {
        // 1. Tenant tree (current production)
        File tenantHit = resolveInTenantTree(new File(sandboxRoot, TENANTS_DIR), sessionId, filename);
        if (tenantHit != null) return tenantHit;
        // 2. Legacy date-bucketed flat
        File flatHit = resolveInDateBucketedTree(new File(sandboxRoot, SESSIONS_DIR), sessionId, filename);
        if (flatHit != null) return flatHit;
        // 3. Pre-date-bucket flat: code-interpreter/{sessionId}/{filename}
        File preDateBucket = new File(new File(sandboxRoot, sessionId), filename);
        return preDateBucket.isFile() ? preDateBucket : null;
    }

    /**
     * Scans {@code tenants/{agentId}/{conversationId}/YYYY-MM-DD/{sessionId}/{filename}}.
     * O(agents × conversations × dates) in the worst case but bounded by
     * the cleanup TTL — most dirs are gone within 24h.
     */
    private static File resolveInTenantTree(File tenantsRoot, String sessionId, String filename) {
        if (!tenantsRoot.isDirectory()) return null;
        File[] agentDirs = tenantsRoot.listFiles(File::isDirectory);
        if (agentDirs == null) return null;
        for (File agentDir : agentDirs) {
            File[] convDirs = agentDir.listFiles(File::isDirectory);
            if (convDirs == null) continue;
            for (File convDir : convDirs) {
                File hit = resolveInDateBucketedTree(convDir, sessionId, filename);
                if (hit != null) return hit;
            }
        }
        return null;
    }

    /** Common helper for the {@code YYYY-MM-DD/{sessionId}/{filename}} pattern. */
    private static File resolveInDateBucketedTree(File root, String sessionId, String filename) {
        if (!root.isDirectory()) return null;
        String today = java.time.LocalDate.now(ZoneId.systemDefault()).toString();
        File hot = new File(new File(new File(root, today), sessionId), filename);
        if (hot.isFile()) return hot;
        File[] dateBuckets = root.listFiles(File::isDirectory);
        if (dateBuckets == null || dateBuckets.length == 0) return null;
        java.util.Arrays.sort(dateBuckets, java.util.Comparator
                .comparing(File::getName).reversed());
        for (File bucket : dateBuckets) {
            if (bucket.getName().equals(today)) continue; // already tried
            File candidate = new File(new File(bucket, sessionId), filename);
            if (candidate.isFile()) return candidate;
        }
        return null;
    }

    private static final Map<String, String> EXTENSION_MIME_TYPES = Map.ofEntries(
            Map.entry(".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            Map.entry(".xls", "application/vnd.ms-excel"),
            Map.entry(".csv", "text/csv"),
            Map.entry(".pdf", "application/pdf"),
            Map.entry(".json", "application/json"),
            Map.entry(".png", "image/png"),
            Map.entry(".jpg", "image/jpeg"),
            Map.entry(".jpeg", "image/jpeg"),
            Map.entry(".gif", "image/gif"),
            Map.entry(".svg", "image/svg+xml"),
            Map.entry(".webp", "image/webp"),
            Map.entry(".txt", "text/plain"),
            Map.entry(".html", "text/html"),
            Map.entry(".zip", "application/zip"),
            Map.entry(".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
            Map.entry(".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation")
    );

    private static String mimeTypeFromExtension(String filename) {
        String lower = filename.toLowerCase(Locale.ROOT);
        int dot = lower.lastIndexOf('.');
        if (dot >= 0) {
            String ext = lower.substring(dot);
            String mime = EXTENSION_MIME_TYPES.get(ext);
            if (mime != null) {
                return mime;
            }
        }
        return "application/octet-stream";
    }
}
